-- Migration: 193_seed_brands.sql
-- Purpose: Seed initial brand domains from advertising data
-- These are the top ~380 brands by impression volume from the Integrate dataset

-- Insert brands as 'community' source (awaiting enrichment)
-- ON CONFLICT DO NOTHING to avoid duplicates if re-run
INSERT INTO discovered_brands (domain, brand_name, source_type, has_brand_manifest)
VALUES
  ('amazon.com', 'Amazon', 'community', false),
  ('wbd.com', 'Warner Bros. Discovery', 'community', false),
  ('walmart.com', 'Walmart', 'community', false),
  ('verizon.com', 'Verizon', 'community', false),
  ('progressive.com', 'Progressive', 'community', false),
  ('adobe.com', 'Adobe', 'community', false),
  ('target.com', 'Target', 'community', false),
  ('amazon.co.uk', 'Amazon UK', 'community', false),
  ('disneyplus.com', 'Disney+', 'community', false),
  ('statefarm.com', 'State Farm', 'community', false),
  ('paramountplus.com', 'Paramount+', 'community', false),
  ('amazon.ca', 'Amazon Canada', 'community', false),
  ('bestbuy.com', 'Best Buy', 'community', false),
  ('amazon.de', 'Amazon Germany', 'community', false),
  ('go.com', 'Disney/ABC', 'community', false),
  ('hillspet.com', 'Hill''s Pet Nutrition', 'community', false),
  ('peacocktv.com', 'Peacock', 'community', false),
  ('geico.com', 'GEICO', 'community', false),
  ('amazon.fr', 'Amazon France', 'community', false),
  ('max.com', 'Max', 'community', false),
  ('allstate.com', 'Allstate', 'community', false),
  ('ulta.com', 'Ulta Beauty', 'community', false),
  ('amazon.es', 'Amazon Spain', 'community', false),
  ('mcdonalds.com', 'McDonald''s', 'community', false),
  ('amazon.it', 'Amazon Italy', 'community', false),
  ('lilly.com', 'Eli Lilly', 'community', false),
  ('samsung.com', 'Samsung', 'community', false),
  ('walgreens.com', 'Walgreens', 'community', false),
  ('doordash.com', 'DoorDash', 'community', false),
  ('americanexpress.com', 'American Express', 'community', false),
  ('trulieve.com', 'Trulieve', 'community', false),
  ('homedepot.com', 'The Home Depot', 'community', false),
  ('goarmy.com', 'U.S. Army', 'community', false),
  ('discovery.com', 'Discovery', 'community', false),
  ('xfinity.com', 'Xfinity', 'community', false),
  ('scopely.com', 'Scopely', 'community', false),
  ('youtube.com', 'YouTube', 'community', false),
  ('mounjaro.com', 'Mounjaro', 'community', false),
  ('facebook.com', 'Facebook', 'community', false),
  ('spectrum.com', 'Spectrum', 'community', false),
  ('discover.com', 'Discover', 'community', false),
  ('tiktok.com', 'TikTok', 'community', false),
  ('rbc.com', 'RBC', 'community', false),
  ('capitalone.com', 'Capital One', 'community', false),
  ('dollargeneral.com', 'Dollar General', 'community', false),
  ('livenationentertainment.com', 'Live Nation', 'community', false),
  ('vicks.com', 'Vicks', 'community', false),
  ('google.com', 'Google', 'community', false),
  ('apple.com', 'Apple', 'community', false),
  ('microsoft.com', 'Microsoft', 'community', false),
  ('netflix.com', 'Netflix', 'community', false),
  ('spotify.com', 'Spotify', 'community', false),
  ('uber.com', 'Uber', 'community', false),
  ('lyft.com', 'Lyft', 'community', false),
  ('airbnb.com', 'Airbnb', 'community', false),
  ('nike.com', 'Nike', 'community', false),
  ('adidas.com', 'Adidas', 'community', false),
  ('coca-cola.com', 'Coca-Cola', 'community', false),
  ('pepsi.com', 'Pepsi', 'community', false),
  ('ford.com', 'Ford', 'community', false),
  ('toyota.com', 'Toyota', 'community', false),
  ('honda.com', 'Honda', 'community', false),
  ('bmw.com', 'BMW', 'community', false),
  ('mercedes-benz.com', 'Mercedes-Benz', 'community', false),
  ('chase.com', 'Chase', 'community', false),
  ('bankofamerica.com', 'Bank of America', 'community', false),
  ('wellsfargo.com', 'Wells Fargo', 'community', false),
  ('citi.com', 'Citi', 'community', false),
  ('att.com', 'AT&T', 'community', false),
  ('t-mobile.com', 'T-Mobile', 'community', false),
  ('sprint.com', 'Sprint', 'community', false),
  ('cvs.com', 'CVS', 'community', false),
  ('riteaid.com', 'Rite Aid', 'community', false),
  ('costco.com', 'Costco', 'community', false),
  ('kroger.com', 'Kroger', 'community', false),
  ('lowes.com', 'Lowe''s', 'community', false),
  ('marriott.com', 'Marriott', 'community', false),
  ('hilton.com', 'Hilton', 'community', false),
  ('hyatt.com', 'Hyatt', 'community', false),
  ('delta.com', 'Delta', 'community', false),
  ('united.com', 'United', 'community', false),
  ('aa.com', 'American Airlines', 'community', false),
  ('southwest.com', 'Southwest', 'community', false),
  ('jetblue.com', 'JetBlue', 'community', false),
  ('expedia.com', 'Expedia', 'community', false),
  ('booking.com', 'Booking.com', 'community', false),
  ('trivago.com', 'Trivago', 'community', false),
  ('kayak.com', 'Kayak', 'community', false),
  ('hulu.com', 'Hulu', 'community', false),
  ('hbomax.com', 'HBO Max', 'community', false),
  ('primevideo.com', 'Prime Video', 'community', false),
  ('linkedin.com', 'LinkedIn', 'community', false),
  ('twitter.com', 'Twitter', 'community', false),
  ('instagram.com', 'Instagram', 'community', false),
  ('snapchat.com', 'Snapchat', 'community', false),
  ('pinterest.com', 'Pinterest', 'community', false),
  ('reddit.com', 'Reddit', 'community', false),
  ('ebay.com', 'eBay', 'community', false),
  ('etsy.com', 'Etsy', 'community', false),
  ('wayfair.com', 'Wayfair', 'community', false)
ON CONFLICT (domain) DO NOTHING;
