-- Migration: 206_seed_properties.sql
-- Purpose: (Originally) seed hosted_properties from Scope3 BigQuery snapshot.
--          Now a no-op — the bulk data import has been retired.
--
-- Why: The original migration body was 8.7 MB / ~53k INSERTs (1,250 publishers,
-- 53,422 properties, 62,440 identifiers from a 2026-02-12 Scope3 export). It
-- shipped in every runtime image and aged into a stale snapshot. Production
-- environments have already applied this migration and hold the data in their
-- hosted_properties table — removing the INSERT body does not affect them
-- (Postgres migrations don't re-run on already-applied versions).
--
-- For fresh installs: hosted_properties starts empty. Registry data populates
-- via two production paths:
--   1. User claims — the registry API writes rows keyed by workos_organization_id
--      / created_by_user_id when a publisher registers their domain.
--   2. Discovery crawler — discovered_properties (separate table) is fed by
--      adagents.json crawling and feeds catalog_properties via migration 336.
--
-- See: issue #4778 for the retirement rationale, PR #4773 (Dockerfile asset
-- hygiene that surfaced the 8.7 MB blob).
--
-- Salvage path: the original 1,250 publisher / 53,422 property / 62,440
-- identifier dataset is preserved in git history. To recover it:
--   git show 89619fb060:server/src/db/migrations/206_seed_properties.sql

-- intentional no-op; keep the version slot so schema_migrations stays linear
SELECT 1;
