-- Persistent task store for MCP async tasks.
-- Replaces InMemoryTaskStore so tasks survive across Fly.io instances.
-- Schema generated by @adcp/client getMcpTasksMigration().

CREATE TABLE IF NOT EXISTS adcp_mcp_tasks (
  task_id         TEXT PRIMARY KEY,
  status          TEXT NOT NULL DEFAULT 'working',
  ttl             INTEGER,
  poll_interval   INTEGER NOT NULL DEFAULT 1000,
  status_message  TEXT,
  request_id      TEXT NOT NULL,
  request         JSONB NOT NULL,
  result          JSONB,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at      TIMESTAMPTZ,

  CONSTRAINT adcp_mcp_tasks_valid_status CHECK (
    status IN ('working', 'input_required', 'completed', 'failed', 'cancelled')
  )
);

CREATE INDEX IF NOT EXISTS idx_adcp_mcp_tasks_expires_at
  ON adcp_mcp_tasks(expires_at) WHERE expires_at IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_adcp_mcp_tasks_created_at
  ON adcp_mcp_tasks(created_at);
