-- Generated by scripts/generate-policy-publication-migration.cjs.
-- The checked-in JSON files are authoritative; regenerate this migration rather
-- than editing the data below by hand.
--   static/registry/policies/creative_content_baseline_safety.json
--   static/registry/policies/creative_measurement_approved_collectors.json
--   static/registry/policies/creative_measurement_tracker_limits.json
--   static/registry/policies/creative_resource_limits.json
--   static/registry/policies/creative_security_auto_redirect.json
--   static/registry/policies/creative_security_credential_harvest.json
--   static/registry/policies/creative_security_deceptive_destination.json
--   static/registry/policies/creative_security_https_only.json
--   static/registry/policies/creative_security_impression_manipulation.json
--   static/registry/policies/creative_security_malicious_code.json
--   static/registry/policies/creative_security_risky_network_origin.json
--   static/registry/policies/creative_ux_non_intrusive.json
--
-- The conflict guard intentionally updates only the same authoritative version.
-- A different version already present in the registry is left untouched, so a
-- delayed or repeated deployment cannot replace a later publication.

WITH incoming AS (
  SELECT entry
  FROM jsonb_array_elements(
$registry_policies$
[
  {
    "policy_id": "creative_content_baseline_safety",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative baseline content-safety standard",
    "description": "Establishes a baseline prohibition on hateful, graphic, shocking, and similarly unsafe creative content.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "brand_safety"
    ],
    "governance_domains": [
      "creative",
      "content_standards"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative must not contain hateful attacks against protected groups, explicit celebration or instruction of serious violence, graphic injury or gore used primarily for shock, or explicit sexual material. Sellers applying additional suitability restrictions such as profanity, suggestive themes, or regulated product categories must use a more specific registry or inline policy rather than expanding this baseline silently. A seller that detects content prohibited by this baseline must reject the creative and identify this policy.",
    "guidance": "Evaluate the creative itself, not adjacent publisher content. Apply category-specific policies for alcohol, gambling, political, pharmaceutical, weapons, and other regulated advertising. Buyer remediation: replace the prohibited text, imagery, audio, or video rather than making a cosmetic resubmission.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A fictional outdoor-equipment advertiser shows adults hiking on a rocky trail with no graphic injury, hate-based content, or explicit material.",
          "explanation": "The creative does not contain any content prohibited by the baseline."
        }
      ],
      "fail": [
        {
          "scenario": "A shock advertisement uses a graphic close-up of a severe real-world injury as its primary attention mechanism.",
          "explanation": "Graphic injury used primarily for shock violates the baseline safety policy."
        }
      ]
    }
  },
  {
    "policy_id": "creative_measurement_approved_collectors",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative approved-collector requirement",
    "description": "Restricts creative data collection to the enforcing seller's published accepted collector set.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "measurement_privacy"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "Every third-party data collector, cookie setter, tracking pixel, measurement script, and equivalent endpoint used by an advertising creative must appear in the enforcing seller's published accepted collector set for the selected product. The seller or its governance agent must publish the applicable set and, on failure, identify the unaccepted collector in its detailed report or rejection reason. A creative that invokes an unaccepted collector must be rejected with this policy.",
    "guidance": "Classify endpoints by the entity that receives data, including redirects and nested dependencies. Buyer remediation: remove the collector, replace it with an accepted provider, or use the seller's approval process before resubmitting.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A creative sends measurement events only to collectors listed in the seller's accepted set for the selected product.",
          "explanation": "Every observed collector is accepted under the applicable seller policy."
        }
      ],
      "fail": [
        {
          "scenario": "A measurement script loads a nested tracking pixel operated by a provider absent from the seller's published accepted set.",
          "explanation": "The creative invokes an unaccepted collector, even though it appears through a nested dependency."
        }
      ]
    }
  },
  {
    "policy_id": "creative_measurement_tracker_limits",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative measurement tracker limits",
    "description": "Limits creative tracker count, redirect depth, and measurement waterfall depth to published seller thresholds.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "measurement_privacy"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative's number of measurement trackers, nested measurement dependencies, and redirect or waterfall depth must remain within the limits published by the enforcing seller or its governance agent for the selected product and evaluation profile. The evaluator must publish the applied limits and, on failure, report the exceeded metric and observed value. A seller must not reject under this policy without an applicable published limit. A creative that exceeds an applicable limit must be rejected with this policy.",
    "guidance": "Count nested and dynamically loaded measurement calls, not only top-level declarations. Buyer remediation: remove redundant trackers, consolidate measurement providers, and shorten redirect and waterfall chains.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A creative loads three trackers with one redirect hop where the seller's published limits allow five trackers and two hops.",
          "explanation": "The observed tracker count and redirect depth remain within both applicable limits."
        }
      ],
      "fail": [
        {
          "scenario": "A creative loads nine trackers where the seller's published product limit is five, and the detailed report lists the observed count.",
          "explanation": "The observed tracker count exceeds a disclosed applicable threshold."
        }
      ]
    }
  },
  {
    "policy_id": "creative_resource_limits",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative runtime resource limits",
    "description": "Requires creative CPU, main-thread, memory, and network use to remain within published seller limits.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "user_experience"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative's runtime CPU use, main-thread execution, memory use, and network-request volume must remain within the limits published by the enforcing seller or its governance agent for the selected product and evaluation profile. The evaluator must publish the applied limits and, on failure, report the exceeded metric and observed value. A seller must not reject under this policy without an applicable published limit. A creative that exceeds an applicable limit must be rejected with this policy.",
    "guidance": "Use a reproducible device, network, interaction, and observation profile. Buyer remediation: reduce animation and script work, remove unnecessary dependencies, consolidate requests, and confirm the observed metrics fall below the published limits.",
    "exemplars": {
      "pass": [
        {
          "scenario": "Under the seller's published evaluation profile, a creative stays below every declared CPU, main-thread, memory, and request limit.",
          "explanation": "All measured resource values satisfy the applicable published thresholds."
        }
      ],
      "fail": [
        {
          "scenario": "A looping animation consumes 65% CPU where the seller's published product profile permits at most 30%, and the report identifies both values.",
          "explanation": "The measured CPU use exceeds an applicable, disclosed limit."
        }
      ]
    }
  },
  {
    "policy_id": "creative_security_auto_redirect",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative automatic-navigation prohibition",
    "description": "Prohibits redirects, forced application opens, and click hijacking without deliberate user interaction.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "security"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative must not navigate the top-level browsing context, open an application or application store, synthesize a click, or start a redirect chain unless the user deliberately interacts with a clearly presented control. Navigation caused by timers, page load, pointer movement, invisible overlays, or click interception is prohibited. A seller that detects prohibited navigation must reject the creative and identify this policy.",
    "guidance": "Test the creative before interaction and exercise each visible control. Buyer remediation: remove automatic redirects, forced-open logic, invisible click targets, and click interception; preserve navigation only after explicit user activation.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A user clicks a visible Learn more button and the creative opens the disclosed advertiser landing page.",
          "explanation": "Navigation follows deliberate interaction with a clearly presented control."
        }
      ],
      "fail": [
        {
          "scenario": "Two seconds after rendering, a display tag replaces the publisher page with an application-store destination even though the user did not interact.",
          "explanation": "The creative initiates top-level navigation without user activation."
        }
      ]
    }
  },
  {
    "policy_id": "creative_security_credential_harvest",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative credential-harvesting prohibition",
    "description": "Prohibits deceptive collection of credentials, payment data, and other sensitive information.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "security",
      "brand_safety"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative and its destination must not impersonate another organization or use false urgency, false support claims, or misleading interface elements to obtain passwords, authentication codes, payment credentials, government identifiers, recovery phrases, or other sensitive information. A seller that detects deceptive sensitive-data collection must reject the creative and identify this policy.",
    "guidance": "Evaluate both the rendered creative and reachable destination. Buyer remediation: remove the deceptive collection flow and direct users only to an authenticated, accurately represented destination controlled by the identified advertiser.",
    "exemplars": {
      "pass": [
        {
          "scenario": "An ad from a fictional subscription service links to that service's authenticated domain, where an ordinary checkout clearly identifies the merchant and purchase.",
          "explanation": "The destination accurately identifies the advertiser and does not deceptively solicit credentials."
        }
      ],
      "fail": [
        {
          "scenario": "An ad imitates a bank security alert and links to a look-alike domain that asks the user for a password and one-time authentication code.",
          "explanation": "The creative impersonates an organization to harvest credentials."
        }
      ]
    }
  },
  {
    "policy_id": "creative_security_deceptive_destination",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative deceptive-destination prohibition",
    "description": "Prohibits fake downloads, impersonation, and materially deceptive landing experiences.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "security",
      "brand_safety"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative must not route users to a destination that materially misrepresents its identity, purpose, product, or requested action. Prohibited experiences include fake software or security updates, counterfeit system dialogs, undisclosed impersonation, and landing pages whose material offer or identity contradicts the creative. Credential harvesting is evaluated separately under creative_security_credential_harvest. A seller that detects a deceptive destination must reject the creative and identify this policy.",
    "guidance": "Follow the complete redirect chain and compare the rendered destination with the creative's identity and claims. Buyer remediation: replace the destination, remove impersonating interface elements, and align the creative's claims with the actual service or offer.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A creative advertising a fictional photo editor links to the same advertiser's domain and accurately describes the available application download.",
          "explanation": "The destination identity and offer match the advertising claim."
        }
      ],
      "fail": [
        {
          "scenario": "A banner designed as an operating-system warning says the device is infected and links to an unrelated executable download.",
          "explanation": "The creative uses a counterfeit system message to induce a deceptive download."
        }
      ]
    }
  },
  {
    "policy_id": "creative_security_https_only",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative HTTPS-only resource requirement",
    "description": "Requires every creative network request to use HTTPS in a secure serving environment.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "security"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative served in a secure context must use HTTPS for every asset, script, frame, redirect, tracking request, and other network dependency. An HTTP URL violates this policy even when the initial creative or final destination uses HTTPS. A seller that observes an insecure request must reject the creative and identify this policy.",
    "guidance": "Exercise interactive paths and follow redirects when inspecting requests. Buyer remediation: migrate every dependency and redirect hop to HTTPS, then rerun the evaluation.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A tag and all of its scripts, images, frames, trackers, and redirect hops use HTTPS.",
          "explanation": "The complete dependency chain remains in a secure transport context."
        }
      ],
      "fail": [
        {
          "scenario": "An HTTPS tag loads one impression pixel from an HTTP endpoint.",
          "explanation": "A single insecure network request violates the HTTPS-only requirement."
        }
      ]
    }
  },
  {
    "policy_id": "creative_security_impression_manipulation",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative impression-manipulation prohibition",
    "description": "Prohibits creative-controlled stacking, stuffing, hiding, or duplicate rendering used to inflate impressions.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "security"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative must not create hidden, stacked, stuffed, off-screen, zero-opacity, or duplicate ad renderings or media players for the purpose or effect of generating impressions that are not represented by the seller's intended placement. This policy applies to behavior caused by the creative payload; seller inventory fraud that is not caused by the creative is outside its scope. A seller that detects creative-caused impression manipulation must reject the creative and identify this policy.",
    "guidance": "Inspect the rendered document and network activity for undeclared ad containers or players. Buyer remediation: remove hidden, duplicate, or nested rendering behavior and ensure the payload renders only in the contracted placement.",
    "exemplars": {
      "pass": [
        {
          "scenario": "One display tag renders one visible creative in the contracted slot and fires its declared impression measurement once.",
          "explanation": "The creative represents the intended placement without hidden or duplicate rendering."
        }
      ],
      "fail": [
        {
          "scenario": "A display tag creates several one-pixel off-screen iframes that each load another ad and record an impression.",
          "explanation": "The payload generates hidden, duplicate ad impressions outside the intended placement."
        }
      ]
    }
  },
  {
    "policy_id": "creative_security_malicious_code",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative payload malicious-code prohibition",
    "description": "Prohibits malware, exploit behavior, and unauthorized computing in an advertising payload.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "security",
      "brand_safety"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative and every resource it loads must not contain, install, retrieve, or execute malicious code. Prohibited behavior includes exploiting a device or browser vulnerability, installing malware, gaining unauthorized access, evading security controls, or using the device for unauthorized computation such as cryptocurrency mining. A seller that detects this behavior must reject the creative and identify this policy.",
    "guidance": "Evaluate the executable payload and its dependency chain, not merely the advertiser category. Buyer remediation: replace the compromised or malicious asset, audit its production and hosting supply chain, and resubmit only after a clean evaluation.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A display tag loads declared animation and measurement scripts that render the ad and make no attempt to exploit the browser or perform undeclared computation.",
          "explanation": "Normal rendering and measurement behavior is not malicious code."
        }
      ],
      "fail": [
        {
          "scenario": "A display tag probes for a browser vulnerability and, when present, downloads an executable that runs a cryptocurrency miner.",
          "explanation": "The payload attempts exploitation and unauthorized computation."
        }
      ]
    }
  },
  {
    "policy_id": "creative_security_risky_network_origin",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative risky-network-origin restriction",
    "description": "Requires creative network dependencies to pass the enforcing seller's published origin-risk controls.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "security"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "Every network origin contacted by an advertising creative must satisfy the enforcing seller's published origin-risk controls at evaluation time. The seller or its governance agent must publish the classification methodology and, on failure, identify the rejected origin and current classification in its detailed report or rejection reason. A seller must not use this policy as an unexplained advertiser or account deny-list. A creative that calls an origin classified as unsafe under the published controls must be rejected with this policy.",
    "guidance": "Origin reputation is time-dependent and seller-parameterized. Return the observed origin and classification without disclosing private threat intelligence. Buyer remediation: remove or replace the dependency; use the seller's appeal process when the classification appears incorrect.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A display tag loads only its declared creative host and measurement endpoints, and each passes the seller's published origin-risk checks at evaluation time.",
          "explanation": "Every observed dependency satisfies the enforcing seller's declared controls."
        }
      ],
      "fail": [
        {
          "scenario": "An otherwise ordinary tag loads an obfuscated script from an origin currently classified as malware-distributing by the seller's published evaluation method.",
          "explanation": "The creative depends on an origin that fails the applicable risk controls."
        }
      ]
    }
  },
  {
    "policy_id": "creative_ux_non_intrusive",
    "source": "registry",
    "version": "1.0.0",
    "name": "Creative non-intrusive user-experience standard",
    "description": "Prohibits creative behavior that alters or obstructs the publisher experience without declared permission.",
    "category": "standard",
    "enforcement": "must",
    "jurisdictions": [],
    "policy_categories": [
      "user_experience"
    ],
    "governance_domains": [
      "creative"
    ],
    "effective_date": "2026-08-21",
    "source_url": "https://docs.adcontextprotocol.org/docs/governance/creative/policy-backed-rejections#initial-registry-policies",
    "source_name": "AgenticAdvertising.org",
    "policy": "An advertising creative must remain within the interaction and layout permissions declared by the selected product and format. Unless explicitly permitted, it must not create overlays outside its placement, cover publisher content, open pop-ups or interstitials, become sticky, resize or reflow the publisher page, capture unrelated input, or play audible media without user activation. The seller or its governance agent must publish any permissions it relies on. A seller that detects unauthorized intrusive behavior must reject the creative and identify this policy.",
    "guidance": "Evaluate behavior relative to the selected product and format; an overlay is not a violation when that interaction is explicitly contracted. Buyer remediation: remove the unauthorized behavior or select a product and format that declares support for it.",
    "exemplars": {
      "pass": [
        {
          "scenario": "A creative remains inside its contracted slot and starts audio only after the user selects a visible play control.",
          "explanation": "The creative stays within its placement and audible playback follows deliberate interaction."
        }
      ],
      "fail": [
        {
          "scenario": "A standard display placement injects a full-page overlay and starts audible playback on load even though the product declares neither behavior.",
          "explanation": "The creative obstructs publisher content and plays audio without permission or user activation."
        }
      ]
    }
  }
]
$registry_policies$::jsonb
  ) AS bundled(entry)
)
INSERT INTO policies (
  policy_id,
  version,
  name,
  description,
  category,
  enforcement,
  jurisdictions,
  region_aliases,
  policy_categories,
  channels,
  effective_date,
  sunset_date,
  governance_domains,
  source_url,
  source_name,
  policy,
  guidance,
  exemplars,
  ext,
  source_type,
  review_status
)
SELECT
  entry->>'policy_id',
  entry->>'version',
  entry->>'name',
  entry->>'description',
  entry->>'category',
  entry->>'enforcement',
  COALESCE(entry->'jurisdictions', '[]'::jsonb),
  COALESCE(entry->'region_aliases', '{}'::jsonb),
  COALESCE(entry->'policy_categories', '[]'::jsonb),
  entry->'channels',
  entry->>'effective_date',
  entry->>'sunset_date',
  COALESCE(entry->'governance_domains', '[]'::jsonb),
  entry->>'source_url',
  entry->>'source_name',
  entry->>'policy',
  entry->>'guidance',
  entry->'exemplars',
  entry->'ext',
  'registry',
  'approved'
FROM incoming
ON CONFLICT (policy_id) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  enforcement = EXCLUDED.enforcement,
  jurisdictions = EXCLUDED.jurisdictions,
  region_aliases = EXCLUDED.region_aliases,
  policy_categories = EXCLUDED.policy_categories,
  channels = EXCLUDED.channels,
  effective_date = EXCLUDED.effective_date,
  sunset_date = EXCLUDED.sunset_date,
  governance_domains = EXCLUDED.governance_domains,
  source_url = EXCLUDED.source_url,
  source_name = EXCLUDED.source_name,
  policy = EXCLUDED.policy,
  guidance = EXCLUDED.guidance,
  exemplars = EXCLUDED.exemplars,
  ext = EXCLUDED.ext,
  review_status = 'approved'
WHERE policies.version = EXCLUDED.version
  AND policies.source_type = 'registry';
