-- Generated by scripts/generate-policy-publication-migration.cjs.
-- The checked-in JSON files are authoritative; regenerate this migration rather
-- than editing the data below by hand.
--   static/registry/policies/amazon_political_advertising_acceptance.json
--   static/registry/policies/eu_dsa_political_targeting.json
--   static/registry/policies/google_political_advertising_acceptance.json
--   static/registry/policies/linkedin_political_advertising_acceptance.json
--   static/registry/policies/meta_political_advertising_acceptance.json
--   static/registry/policies/pinterest_political_advertising_acceptance.json
--   static/registry/policies/snap_political_advertising_acceptance.json
--   static/registry/policies/tiktok_political_advertising_acceptance.json
--   static/registry/policies/x_political_advertising_acceptance.json
--   static/registry/policy-versions/eu_dsa_political_targeting/1.0.0.json
--
-- The conflict guard updates the same authoritative version or an explicitly
-- declared predecessor. Any other version is left untouched, so a delayed
-- deployment cannot overwrite a later publication or perform an undeclared
-- version transition.

CREATE TEMP TABLE incoming_policy_publications ON COMMIT DROP AS
WITH bundled AS (
  SELECT payload
  FROM jsonb_array_elements(
$registry_policies$
[
  {
    "entry": {
      "policy_id": "eu_dsa_political_targeting",
      "source": "registry",
      "version": "1.0.0",
      "name": "EU Digital Services Act — Political Ad Targeting Restrictions",
      "description": "Prohibits targeting political advertisements using special categories of personal data under DSA Article 26 and the EU Political Advertising Regulation.",
      "category": "regulation",
      "enforcement": "must",
      "jurisdictions": [
        "AT",
        "BE",
        "BG",
        "HR",
        "CY",
        "CZ",
        "DK",
        "EE",
        "FI",
        "FR",
        "DE",
        "GR",
        "HU",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MT",
        "NL",
        "PL",
        "PT",
        "RO",
        "SK",
        "SI",
        "ES",
        "SE"
      ],
      "region_aliases": {
        "EU": [
          "AT",
          "BE",
          "BG",
          "HR",
          "CY",
          "CZ",
          "DK",
          "EE",
          "FI",
          "FR",
          "DE",
          "GR",
          "HU",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MT",
          "NL",
          "PL",
          "PT",
          "RO",
          "SK",
          "SI",
          "ES",
          "SE"
        ]
      },
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign"
      ],
      "effective_date": "2025-10-14",
      "source_url": "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022R2065",
      "source_name": "European Parliament and Council",
      "policy": "Political advertising in the EU must not use special categories of personal data (GDPR Article 9) for targeting.\n\nSpecific prohibitions:\n1. Targeting based on racial or ethnic origin, political opinions, religious beliefs, trade union membership, health data, sex life or sexual orientation, genetic data, or biometric data is prohibited for political ads.\n2. Profiling that infers special category data (e.g., inferring political opinions from browsing behavior) is also prohibited.\n3. Political ads must include transparency labels identifying the sponsor and funding source.\n4. Targeting criteria used must be disclosed in an ad transparency repository.\n\nThe EU Political Advertising Regulation (effective October 2025) further restricts targeting techniques for political advertising to only contextual, linguistic, and broad geographic criteria.",
      "guidance": "This policy intersects with the restricted_attributes mechanism. When a plan declares policy_categories: ['political_advertising'], governance agents should automatically restrict all GDPR Article 9 categories. The DSA and Political Advertising Regulation effectively limit political ad targeting to contextual and broad geographic methods.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A political party runs ads in Germany using only German-language targeting and broad geographic targeting (Bundesland level) with no demographic or interest-based audience segments.",
            "explanation": "Contextual, linguistic, and broad geographic targeting are permitted for political advertising under the EU Political Advertising Regulation."
          }
        ],
        "fail": [
          {
            "scenario": "A political campaign targets voters in France using audience segments based on inferred political leaning and religious affiliation.",
            "explanation": "Targeting political ads using inferred political opinions or religious beliefs constitutes use of GDPR Article 9 special category data, which is prohibited under DSA Article 26."
          }
        ]
      }
    },
    "content_digest": "sha256:d606d004b8a91c514a666b82e4167f6c903fef21ac97236a1dbffc4c1d9db6f4",
    "is_current": false
  },
  {
    "entry": {
      "policy_id": "amazon_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "Amazon Ads Political Advertising Acceptance",
      "description": "Amazon Ads prohibition on political campaigns, candidates, parties, elections, and public-issue advocacy.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2026-06-25",
      "source_url": "https://advertising.amazon.com/help/GZS8A5XCFQJTS88N",
      "source_name": "Amazon Ads",
      "issuer": {
        "domain": "amazon.com",
        "name": "Amazon"
      },
      "acceptance_profile": {
        "profile_id": "amazon_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:81b80b7edb40508c97daf2f74493f2e2cb391e4a2025bf50b9a1bc6331d215b9",
        "policy_refs": [
          {
            "policy_id": "amazon_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:5c7dbfca6637dcc5c7d52c03534cfe929d6c21b5c71491be5e08693448cc4aa4"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "delivery"
          ],
          "all_jurisdictions": true
        },
        "description": "Reusable coarse profile of Amazon Ads' public political-advertising acceptance policy.",
        "rules": [
          {
            "rule_id": "amazon_political_prohibited",
            "effective_at": "2026-06-25T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation",
              "political_merchandise"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "delivery"
            ],
            "disposition": "prohibited",
            "policy_ids": [
              "amazon_political_advertising_acceptance"
            ],
            "description": "Political campaigns, candidates, parties, elections, public-issue advocacy, and political merchandise are not accepted."
          }
        ]
      },
      "policy": "Advertising for political campaigns, candidates, political parties, elections, and public issues intended to influence political outcomes is prohibited under the operator's advertising acceptance policies. Product eligibility does not override the prohibition when the advertisement or promoted merchandise is political.",
      "guidance": "Represent political-advertising facets as prohibited unless a more specific current issuer rule establishes an exception. Evaluate both creative message and promoted product or merchandise.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A seller advertises an ordinary consumer product with no political messaging or political merchandising.",
            "explanation": "The advertisement is outside the political prohibition."
          }
        ],
        "fail": [
          {
            "scenario": "An advertiser promotes merchandise designed to support a political candidate.",
            "explanation": "Political campaign advertising and political products are prohibited."
          }
        ]
      }
    },
    "content_digest": "sha256:5c7dbfca6637dcc5c7d52c03534cfe929d6c21b5c71491be5e08693448cc4aa4",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "eu_dsa_political_targeting",
      "source": "registry",
      "version": "2.0.0",
      "name": "EU Political Advertising Regulation — Transparency and Targeting",
      "description": "Regulation (EU) 2024/900 transparency, sponsor-eligibility, targeting, and ad-delivery requirements for political advertising.",
      "category": "regulation",
      "enforcement": "must",
      "jurisdictions": [
        "AT",
        "BE",
        "BG",
        "HR",
        "CY",
        "CZ",
        "DK",
        "EE",
        "FI",
        "FR",
        "DE",
        "GR",
        "HU",
        "IE",
        "IT",
        "LV",
        "LT",
        "LU",
        "MT",
        "NL",
        "PL",
        "PT",
        "RO",
        "SK",
        "SI",
        "ES",
        "SE"
      ],
      "region_aliases": {
        "EU": [
          "AT",
          "BE",
          "BG",
          "HR",
          "CY",
          "CZ",
          "DK",
          "EE",
          "FI",
          "FR",
          "DE",
          "GR",
          "HU",
          "IE",
          "IT",
          "LV",
          "LT",
          "LU",
          "MT",
          "NL",
          "PL",
          "PT",
          "RO",
          "SK",
          "SI",
          "ES",
          "SE"
        ]
      },
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign"
      ],
      "effective_date": "2025-10-10",
      "source_url": "https://eur-lex.europa.eu/eli/reg/2024/900/oj/eng",
      "source_name": "European Parliament and Council",
      "policy": "Political advertising disseminated in the Union, brought into the public domain in a Member State, or directed to Union citizens must comply with Regulation (EU) 2024/900.\n\n1. Political advertisements must carry the required label and transparency notice, including sponsor and targeting information.\n2. Targeting or ad-delivery techniques must not involve profiling using GDPR Article 9 special categories of personal data.\n3. Other personal data may be used for online political-ad targeting or delivery only when collected from the data subject with separate explicit consent for political advertising.\n4. Targeting a person known with reasonable certainty to be at least one year below the applicable voting age is prohibited.\n5. During the final three months before an EU or Member State election or referendum, the sponsor must meet the Regulation's Union citizenship, residence, establishment, ownership, or control criteria.\n6. Official election-participation information and qualifying official public information are excluded from the political-advertising definition when they are not designed to influence an outcome, voting behavior, or a legislative or regulatory process.",
      "guidance": "This policy intersects with restricted_attributes and political_advertising facets. Governance agents should restrict every GDPR Article 9 category, not only political opinions, and separately evaluate consent, minor, transparency, sponsor-eligibility, and official-information exception requirements.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A political advertiser supplies the required transparency notice and uses contextual placement and broad geography without processing personal data to select recipients.",
            "explanation": "The campaign avoids personal-data targeting and provides the required political-ad transparency information."
          }
        ],
        "fail": [
          {
            "scenario": "A political campaign targets voters in France using audience segments based on inferred political leaning and religious affiliation.",
            "explanation": "Regulation (EU) 2024/900 Article 18 prohibits profiling for political-ad targeting or delivery using GDPR Article 9 special-category data."
          }
        ]
      }
    },
    "content_digest": "sha256:6c375f47c68b3655a607a4e3a5fad211c20efab4bea4e0f2d8ee190b2080bc43",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "google_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "Google Political Content Advertising Acceptance",
      "description": "Google market-specific political-content eligibility, verification, disclosure, targeting, blackout, and regional prohibition rules.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2025-09-01",
      "source_url": "https://support.google.com/displayvideo/answer/6014595?hl=en",
      "source_name": "Google",
      "issuer": {
        "domain": "google.com",
        "name": "Google"
      },
      "acceptance_profile": {
        "profile_id": "google_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:29bf0717dec7f6a587d1f5aa27f23b0b38e639478d5e9b8ccb49259ca33d120d",
        "policy_refs": [
          {
            "policy_id": "google_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:731e77b1d89976bee3b173741066e80b8919f0af20a80a50ca89e7d8ce92afe1"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "targeting",
            "delivery"
          ],
          "all_jurisdictions": true
        },
        "region_aliases": {
          "EU": [
            "AT",
            "BE",
            "BG",
            "HR",
            "CY",
            "CZ",
            "DK",
            "EE",
            "FI",
            "FR",
            "DE",
            "GR",
            "HU",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MT",
            "NL",
            "PL",
            "PT",
            "RO",
            "SK",
            "SI",
            "ES",
            "SE"
          ]
        },
        "description": "Reusable coarse profile of Google's public political-content advertising acceptance policy.",
        "rules": [
          {
            "rule_id": "google_political_conditional",
            "effective_at": "2025-09-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "targeting",
              "delivery"
            ],
            "disposition": "conditional",
            "requirements": [
              {
                "kind": "advertiser_verification",
                "verification_scheme": "google_election_ads_verification"
              },
              {
                "kind": "disclosure",
                "format": "sponsor_identity",
                "placement": "creative"
              },
              {
                "kind": "targeting_restriction",
                "description": "Use only geographic and demographic targeting permitted for the election type and market."
              },
              {
                "kind": "creative_restriction",
                "description": "Provide any required synthetic or digitally altered content disclosure."
              },
              {
                "kind": "time_restriction",
                "description": "Observe election-specific blackout periods."
              }
            ],
            "policy_ids": [
              "google_political_advertising_acceptance"
            ],
            "description": "In supported non-prohibited markets, political content is conditional on market-specific verification, disclosure, targeting, content, and timing requirements."
          },
          {
            "rule_id": "google_eu_political_prohibited",
            "effective_at": "2025-09-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation",
              "political_merchandise"
            ],
            "jurisdiction_groups": [
              "EU"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "targeting",
              "delivery"
            ],
            "disposition": "prohibited",
            "policy_ids": [
              "google_political_advertising_acceptance"
            ],
            "description": "Political advertising covered by the operator's EU policy is not accepted for EU delivery."
          },
          {
            "rule_id": "google_eu_official_information_conditional",
            "effective_at": "2025-09-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "government_information"
            ],
            "advertiser_roles": [
              "government_entity",
              "election_authority"
            ],
            "jurisdiction_groups": [
              "EU"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "delivery"
            ],
            "disposition": "conditional",
            "requirements": [
              {
                "kind": "advertiser_eligibility",
                "criteria": [
                  "official_public_authority_or_election_participation_source"
                ]
              },
              {
                "kind": "prior_authorization",
                "description": "Apply for and receive the operator's official-information exception before delivery."
              },
              {
                "kind": "creative_restriction",
                "description": "Content must be non-persuasive official information or qualifying election-participation information."
              }
            ],
            "policy_ids": [
              "google_political_advertising_acceptance"
            ],
            "description": "Qualifying official public information may be considered only through the operator's application-based exception."
          }
        ]
      },
      "policy": "Political content acceptance varies by delivery region and election type. Where accepted, advertisers may need election-ad verification, identity and sponsor disclosures, restricted geographic and demographic targeting, synthetic-content disclosure, and compliance with election-specific blackout periods. Some official government information and qualifying news content may be treated differently. Political advertising as defined by EU Regulation 2024/900 is prohibited for European Union delivery, subject to an application-based exception for qualifying official election-participation messages and non-persuasive public-authority information.",
      "guidance": "Resolve this entry with current region-specific issuer guidance. Treat ordinary EU political delivery as prohibited, the defined EU official-information exception as conditional, and political delivery in other supported regions as conditional unless a more specific current issuer policy defines another result.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A verified advertiser in a supported market supplies the required election disclosure and uses targeting permitted for that election type.",
            "explanation": "The request satisfies the coarse conditional-acceptance requirements for a supported market."
          }
        ],
        "fail": [
          {
            "scenario": "A buyer declares political content but requests that the campaign serve to users in EU member states.",
            "explanation": "The operator's EU policy does not accept political advertising for EU delivery."
          }
        ]
      }
    },
    "content_digest": "sha256:731e77b1d89976bee3b173741066e80b8919f0af20a80a50ca89e7d8ce92afe1",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "linkedin_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "LinkedIn Political Advertising Acceptance",
      "description": "LinkedIn prohibition on political advertising.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2025-11-18",
      "source_url": "https://www.linkedin.com/legal/ads-policy",
      "source_name": "LinkedIn",
      "issuer": {
        "domain": "linkedin.com",
        "name": "LinkedIn"
      },
      "acceptance_profile": {
        "profile_id": "linkedin_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:e2683041e6abb6b8d8d2b8210bfd35d7334e24781edf6cef29f6b10816561c63",
        "policy_refs": [
          {
            "policy_id": "linkedin_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:04a5cf5c6262a60f378e83043b46677372c4ed2378f9930565278105113defd1"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "delivery"
          ],
          "all_jurisdictions": true
        },
        "description": "Reusable coarse profile of LinkedIn's public political-advertising acceptance policy.",
        "rules": [
          {
            "rule_id": "linkedin_political_prohibited",
            "effective_at": "2025-11-18T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "delivery"
            ],
            "disposition": "prohibited",
            "policy_ids": [
              "linkedin_political_advertising_acceptance"
            ],
            "description": "Candidate, party, ballot, legislative, election-influence, fundraising, and sensitive political-issue advertising is not accepted."
          }
        ]
      },
      "policy": "Political advertising is prohibited. This includes advertising for or against candidates, parties, ballot propositions, laws or regulations; election-influence advertising; political fundraising; and advertising that exploits a sensitive political issue even without an explicit political agenda. Sellers should apply the current issuer definition and should not infer an exception from advertiser industry alone.",
      "guidance": "Represent candidate_or_party, election_or_ballot_measure, issue_advocacy, and legislation_or_regulation as prohibited. Editorial or incidental content should be evaluated against the issuer's current definition rather than automatically classified as paid political advertising.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A commercial campaign without political advocacy promotes an ordinary business service.",
            "explanation": "The request is outside the political-advertising category."
          }
        ],
        "fail": [
          {
            "scenario": "An organization purchases an advertisement urging voters to oppose a ballot proposition.",
            "explanation": "Paid ballot-measure advocacy is prohibited political advertising."
          }
        ]
      }
    },
    "content_digest": "sha256:04a5cf5c6262a60f378e83043b46677372c4ed2378f9930565278105113defd1",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "meta_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "Meta Political, Electoral, and Social-Issue Advertising Acceptance",
      "description": "Meta acceptance, authorization, disclosure, archive, targeting, blackout, synthetic-content, and regional availability rules for political, electoral, and social-issue advertising.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2025-10-06",
      "source_url": "https://about.fb.com/news/2025/07/ending-political-electoral-and-social-issue-advertising-in-the-eu/",
      "source_name": "Meta",
      "issuer": {
        "domain": "meta.com",
        "name": "Meta"
      },
      "acceptance_profile": {
        "profile_id": "meta_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:7584e8e357a69501b43e9cff6e18ae811355d6765bd1c13b11433ccc79dc32fe",
        "policy_refs": [
          {
            "policy_id": "meta_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:a8d61d10c9fc04ae7a0af83870f65b92987b9c0a7519d5724afabbbea30b25fc"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "targeting",
            "delivery"
          ],
          "all_jurisdictions": true
        },
        "region_aliases": {
          "EU": [
            "AT",
            "BE",
            "BG",
            "HR",
            "CY",
            "CZ",
            "DK",
            "EE",
            "FI",
            "FR",
            "DE",
            "GR",
            "HU",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MT",
            "NL",
            "PL",
            "PT",
            "RO",
            "SK",
            "SI",
            "ES",
            "SE"
          ]
        },
        "description": "Reusable coarse profile of Meta's public political, electoral, and social-issue advertising acceptance policy.",
        "rules": [
          {
            "rule_id": "meta_political_conditional",
            "effective_at": "2025-10-06T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "targeting",
              "delivery"
            ],
            "disposition": "conditional",
            "requirements": [
              {
                "kind": "category_declaration",
                "declaration": "political_electoral_or_social_issue"
              },
              {
                "kind": "advertiser_verification",
                "verification_scheme": "meta_identity_and_location_authorization"
              },
              {
                "kind": "disclosure",
                "format": "paid_for_by",
                "placement": "creative"
              },
              {
                "kind": "targeting_restriction",
                "description": "Use only targeting permitted for the applicable political or social-issue category and market."
              },
              {
                "kind": "creative_restriction",
                "description": "Disclose qualifying digitally created or altered content."
              },
              {
                "kind": "time_restriction",
                "description": "Observe designated election blackout periods."
              },
              {
                "kind": "transparency_reporting",
                "description": "Permit retention in the operator's public advertising archive."
              }
            ],
            "policy_ids": [
              "meta_political_advertising_acceptance"
            ],
            "description": "In supported non-prohibited markets, political, electoral, and social-issue advertising is conditional on authorization and market-specific restrictions."
          },
          {
            "rule_id": "meta_eu_political_prohibited",
            "effective_at": "2025-10-06T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation",
              "political_merchandise"
            ],
            "jurisdiction_groups": [
              "EU"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "targeting",
              "delivery"
            ],
            "disposition": "prohibited",
            "policy_ids": [
              "meta_political_advertising_acceptance"
            ],
            "description": "Political, electoral, and social-issue advertising is not accepted for EU delivery."
          }
        ]
      },
      "policy": "Political, electoral, and qualifying social-issue advertising is subject to market-specific acceptance. Advertisers must declare the applicable special ad category. Where accepted, advertisers may be required to complete identity and location authorization, supply a paid-for-by disclosure, comply with restricted targeting, disclose qualifying digitally created or altered content, and allow the advertisement to be retained in a public archive. New political advertisements may be restricted during designated election blackout periods. Political, electoral, and social-issue advertisements are not accepted for delivery in the European Union under the operator policy effective 6 October 2025. Exact eligibility, targeting, disclosure, and timing rules vary by delivery market and advertiser role.",
      "guidance": "Resolve this policy by delivery jurisdiction and political-advertising facet. Treat EU delivery as prohibited and supported non-EU markets as conditional unless a more specific current issuer policy says otherwise. Discovery does not replace the operator's authorization or creative review.",
      "exemplars": {
        "pass": [
          {
            "scenario": "An authorized advertiser in a supported market declares the political category, supplies the required sponsor disclosure, uses permitted targeting, and submits outside a blackout window.",
            "explanation": "The campaign satisfies the coarse acceptance prerequisites; final operator review still applies."
          }
        ],
        "fail": [
          {
            "scenario": "An advertiser requests delivery of a political advertisement in an EU member state after 6 October 2025.",
            "explanation": "The operator does not accept political, electoral, or social-issue advertising for EU delivery."
          }
        ]
      }
    },
    "content_digest": "sha256:a8d61d10c9fc04ae7a0af83870f65b92987b9c0a7519d5724afabbbea30b25fc",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "pinterest_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "Pinterest Political Advertising Acceptance",
      "description": "Pinterest prohibition on political campaigning, election influence, legislative advocacy, and political merchandise advertising.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2018-01-01",
      "source_url": "https://policy.pinterest.com/en/advertising-guidelines",
      "source_name": "Pinterest",
      "issuer": {
        "domain": "pinterest.com",
        "name": "Pinterest"
      },
      "acceptance_profile": {
        "profile_id": "pinterest_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:5ed360814d592d9271157912db6c19709d0090bf287d4192234df945205f1b93",
        "policy_refs": [
          {
            "policy_id": "pinterest_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:f47f6ad9d15f6576cd3db45b272de729afddc72068836077b6dd276f0127f7b6"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "delivery"
          ],
          "all_jurisdictions": true
        },
        "description": "Reusable coarse profile of Pinterest's public political-advertising acceptance policy.",
        "rules": [
          {
            "rule_id": "pinterest_political_prohibited",
            "effective_at": "2018-01-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "legislation_or_regulation",
              "political_merchandise"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "delivery"
            ],
            "disposition": "prohibited",
            "policy_ids": [
              "pinterest_political_advertising_acceptance"
            ],
            "description": "Political campaigning, election influence, legislative advocacy, referendums, and political campaign merchandise are not accepted."
          }
        ]
      },
      "policy": "Political campaigning and election advertising is prohibited, including advertising for candidates or parties, content intended to influence elections, legislation, or referendums, and political campaign merchandise. The current issuer guidelines control classification of adjacent public-issue and incidental content.",
      "guidance": "Represent candidate_or_party, election_or_ballot_measure, legislation_or_regulation, and political_merchandise as prohibited. Evaluate issue advocacy under the current issuer definition.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A non-political retailer advertises an ordinary household product without campaign or issue messaging.",
            "explanation": "The advertisement is outside the prohibited political categories."
          }
        ],
        "fail": [
          {
            "scenario": "A store advertises merchandise bearing a candidate campaign slogan.",
            "explanation": "Political campaign merchandise advertising is prohibited."
          }
        ]
      }
    },
    "content_digest": "sha256:f47f6ad9d15f6576cd3db45b272de729afddc72068836077b6dd276f0127f7b6",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "snap_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "Snap Political Advertising Acceptance",
      "description": "Snap conditional acceptance and review requirements for election, advocacy, and issue advertising.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2025-10-01",
      "source_url": "https://www.snap.com/ad-policies/political",
      "source_name": "Snap",
      "issuer": {
        "domain": "snap.com",
        "name": "Snap"
      },
      "acceptance_profile": {
        "profile_id": "snap_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:06efe90e2adaded02529acc7a48be5e2e283020b3194a00a78aa0dc3e59ec0a0",
        "policy_refs": [
          {
            "policy_id": "snap_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:22160b18384dd9ad4add60b24a9d4e862c9f8d179139c27a235098f7e5f6f96d"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "targeting",
            "delivery"
          ],
          "all_jurisdictions": true
        },
        "region_aliases": {
          "EU": [
            "AT",
            "BE",
            "BG",
            "HR",
            "CY",
            "CZ",
            "DK",
            "EE",
            "FI",
            "FR",
            "DE",
            "GR",
            "HU",
            "IE",
            "IT",
            "LV",
            "LT",
            "LU",
            "MT",
            "NL",
            "PL",
            "PT",
            "RO",
            "SK",
            "SI",
            "ES",
            "SE"
          ]
        },
        "description": "Reusable coarse profile of Snap's public political-advertising acceptance policy.",
        "rules": [
          {
            "rule_id": "snap_political_conditional",
            "effective_at": "2025-10-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "targeting",
              "delivery"
            ],
            "disposition": "conditional",
            "requirements": [
              {
                "kind": "advertiser_eligibility",
                "criteria": [
                  "eligible_market_residency"
                ],
                "description": "Satisfy advertiser-residency and market-specific eligibility rules."
              },
              {
                "kind": "funding_restriction",
                "criteria": [
                  "sponsor_identity_required",
                  "market_specific_foreign_funding_rules"
                ]
              },
              {
                "kind": "prior_authorization",
                "description": "Submit for operator review and any required fact-checking."
              },
              {
                "kind": "disclosure",
                "format": "paid_for_by",
                "placement": "creative"
              },
              {
                "kind": "targeting_restriction",
                "description": "Use only targeting permitted for the delivery market and political-advertising type."
              },
              {
                "kind": "transparency_reporting",
                "description": "Permit publication in the operator's political-ad transparency library."
              }
            ],
            "policy_ids": [
              "snap_political_advertising_acceptance"
            ],
            "description": "Election, advocacy, and issue advertising is accepted only after eligibility, disclosure, review, targeting, and transparency conditions are met."
          },
          {
            "rule_id": "snap_eu_political_prohibited",
            "effective_at": "2025-10-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation"
            ],
            "jurisdiction_groups": [
              "EU"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "targeting",
              "delivery"
            ],
            "disposition": "prohibited",
            "policy_ids": [
              "snap_political_advertising_acceptance"
            ],
            "description": "Political advertising covered by EU Regulation 2024/900 is not accepted for EU delivery."
          }
        ]
      },
      "policy": "Election-related, advocacy, and issue advertising may be accepted subject to case-by-case review. Advertisements must include the required paid-for-by disclosure and comply with transparency-library requirements. Advertiser residency, foreign-funding, jurisdiction, targeting, and content restrictions may apply. The operator may review and fact-check political advertisements before or during delivery.",
      "guidance": "Represent political advertising as conditional. Discovery should disclose sponsor identification, review, transparency, and market-eligibility requirement classes without promising approval.",
      "exemplars": {
        "pass": [
          {
            "scenario": "An eligible domestic sponsor submits an issue advertisement with the required paid-for-by disclosure for review and transparency publication.",
            "explanation": "The submission satisfies the coarse prerequisites but remains subject to review."
          }
        ],
        "fail": [
          {
            "scenario": "An undisclosed foreign funder attempts to run election advocacy in a market that restricts foreign-funded political advertising.",
            "explanation": "The advertiser and funding arrangement fail the market-specific eligibility rules."
          }
        ]
      }
    },
    "content_digest": "sha256:22160b18384dd9ad4add60b24a9d4e862c9f8d179139c27a235098f7e5f6f96d",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "tiktok_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "TikTok Politics, Government, and Elections Advertising Acceptance",
      "description": "TikTok prohibition on paid political advertising and controlled exceptions for eligible government and election-authority information.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2026-07-01",
      "source_url": "https://ads.tiktok.com/help/article/tiktok-ads-policy-politics-government-and-elections",
      "source_name": "TikTok",
      "issuer": {
        "domain": "tiktok.com",
        "name": "TikTok"
      },
      "acceptance_profile": {
        "profile_id": "tiktok_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:7445c38199ee65a6a7f5689e5718c4f843d6a3c28bc61040511135fde30c8f19",
        "policy_refs": [
          {
            "policy_id": "tiktok_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:abd3a1b39a93c2a03c43843efe9e01dd13870c9a7633d7e1e2732a9d9a511e3f"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "landing_page",
            "targeting",
            "delivery"
          ],
          "all_jurisdictions": true
        },
        "description": "Reusable coarse profile of TikTok's public politics, government, and elections acceptance policy.",
        "rules": [
          {
            "rule_id": "tiktok_paid_political_prohibited",
            "effective_at": "2026-07-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation",
              "political_merchandise"
            ],
            "advertiser_roles": [
              "political_actor",
              "commercial_advertiser"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "delivery"
            ],
            "disposition": "prohibited",
            "policy_ids": [
              "tiktok_political_advertising_acceptance"
            ],
            "description": "Paid political advertising and advertising by political figures or political entities is not accepted."
          },
          {
            "rule_id": "tiktok_government_information_conditional",
            "effective_at": "2026-07-01T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "government_information"
            ],
            "advertiser_roles": [
              "government_entity",
              "election_authority",
              "intergovernmental_organization"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "landing_page",
              "targeting",
              "delivery"
            ],
            "disposition": "conditional",
            "requirements": [
              {
                "kind": "advertiser_verification",
                "verification_scheme": "tiktok_government_account_verification"
              },
              {
                "kind": "account_setup",
                "description": "Use an operator-approved government or election-authority account."
              },
              {
                "kind": "prior_authorization",
                "description": "Complete the controlled onboarding and certification process before submission."
              },
              {
                "kind": "creative_restriction",
                "description": "Content must be factual participation or public-service information and must not advocate a political outcome."
              },
              {
                "kind": "targeting_restriction",
                "description": "Use only targeting permitted for the approved exception and market."
              }
            ],
            "policy_ids": [
              "tiktok_political_advertising_acceptance"
            ],
            "description": "Verified government and election-authority information may qualify only through the controlled exception process."
          }
        ]
      },
      "policy": "Paid political advertising and advertising by political figures or political entities is prohibited. Eligible government, intergovernmental, and election-authority advertisers may advertise only through the operator's controlled onboarding and certification process. Permitted election-authority advertising must be factual and limited to participation information rather than persuasion. Additional market, targeting, age, gender, landing-page, and account restrictions apply to an accepted exception.",
      "guidance": "Default political_actor, candidate_or_party, election_or_ballot_measure, issue_advocacy, and legislation_or_regulation advertising to prohibited. Evaluate government_information only as a conditional exception with the required advertiser role and onboarding.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A verified election authority uses an approved account to publish factual voting-location and participation information without advocating an outcome.",
            "explanation": "Official election participation information can qualify for the controlled government-information exception."
          }
        ],
        "fail": [
          {
            "scenario": "A candidate campaign attempts to purchase a video advertisement asking viewers to vote for the candidate.",
            "explanation": "Paid candidate and campaign advertising is prohibited."
          }
        ]
      }
    },
    "content_digest": "sha256:abd3a1b39a93c2a03c43843efe9e01dd13870c9a7633d7e1e2732a9d9a511e3f",
    "is_current": true
  },
  {
    "entry": {
      "policy_id": "x_political_advertising_acceptance",
      "source": "registry",
      "version": "1.1.0",
      "name": "X Political Content Advertising Acceptance",
      "description": "X conditional political-content and campaigning acceptance by country, advertiser eligibility, certification, format, targeting, and election timing.",
      "category": "standard",
      "enforcement": "must",
      "jurisdictions": [],
      "policy_categories": [
        "political_advertising"
      ],
      "governance_domains": [
        "campaign",
        "creative"
      ],
      "effective_date": "2023-08-29",
      "source_url": "https://business.x.com/en/help/ads-policies/ads-content-policies/political-content",
      "source_name": "X",
      "issuer": {
        "domain": "x.com",
        "name": "X"
      },
      "acceptance_profile": {
        "profile_id": "x_political_advertising_acceptance",
        "version": "1.0.0",
        "content_digest": "sha256:7df1787ce5458151286e80a00e7e1058f72850315e24626fb69458703c994f72",
        "policy_refs": [
          {
            "policy_id": "x_political_advertising_acceptance",
            "version": "1.1.0",
            "content_digest": "sha256:3d5133d0d6d5393bc843da4ccf78aaacb83a3295271754a668aa6b0695df3ad3"
          }
        ],
        "coverage": "partial",
        "scope": {
          "subject_categories": [
            "political_advertising"
          ],
          "applies_to": [
            "account",
            "media_buy",
            "creative",
            "targeting",
            "delivery",
            "format"
          ],
          "all_jurisdictions": true
        },
        "description": "Reusable coarse profile of X's public political-content advertising acceptance policy.",
        "rules": [
          {
            "rule_id": "x_political_conditional_supported_markets",
            "effective_at": "2023-08-29T00:00:00Z",
            "subject_category": "political_advertising",
            "subject_facets": [
              "candidate_or_party",
              "election_or_ballot_measure",
              "issue_advocacy",
              "legislation_or_regulation"
            ],
            "applies_to": [
              "account",
              "media_buy",
              "creative",
              "targeting",
              "delivery",
              "format"
            ],
            "disposition": "conditional",
            "requirements": [
              {
                "kind": "certification",
                "credential": "x_political_content_advertiser_certification"
              },
              {
                "kind": "advertiser_eligibility",
                "criteria": [
                  "supported_delivery_market",
                  "market_specific_domestic_entity_or_residency"
                ]
              },
              {
                "kind": "funding_restriction",
                "criteria": [
                  "market_specific_funding_rules"
                ]
              },
              {
                "kind": "format_restriction",
                "description": "Use only political-content advertising formats permitted for the market."
              },
              {
                "kind": "targeting_restriction",
                "description": "Use only political-content targeting permitted for the market."
              },
              {
                "kind": "time_restriction",
                "description": "Observe applicable election silence and blackout periods."
              }
            ],
            "policy_ids": [
              "x_political_advertising_acceptance"
            ],
            "description": "Political campaigning is conditional in supported markets; this partial profile does not imply acceptance in an unlisted or unknown market."
          }
        ]
      },
      "policy": "Political campaigning advertisements are accepted only in specified countries and subject to certification. Eligible advertisers must satisfy applicable domestic-entity, residency, funding, and local-law requirements. Only permitted formats and constrained targeting may be used, and election silence or blackout periods apply where required. Qualifying news reporting may be exempt when it is not purchased by or coordinated with a political actor.",
      "guidance": "Model political advertising as conditional only for a supported delivery market. Unsupported markets are prohibited. Certification, advertiser location, format, targeting, and time restrictions are separate requirements.",
      "exemplars": {
        "pass": [
          {
            "scenario": "A certified domestic advertiser in a supported country uses an eligible format and targeting configuration outside the applicable silence period.",
            "explanation": "The campaign meets the coarse market and certification conditions."
          }
        ],
        "fail": [
          {
            "scenario": "A foreign political organization requests campaigning delivery in a market that requires a domestic advertiser.",
            "explanation": "The advertiser does not satisfy the market-specific eligibility rule."
          }
        ]
      }
    },
    "content_digest": "sha256:3d5133d0d6d5393bc843da4ccf78aaacb83a3295271754a668aa6b0695df3ad3",
    "is_current": true
  }
]
$registry_policies$::jsonb
  ) AS bundled(payload)
)
SELECT
  payload->'entry' AS entry,
  payload->>'content_digest' AS content_digest,
  (payload->>'is_current')::boolean AS is_current
FROM bundled;

INSERT INTO policy_publications (
  policy_id,
  version,
  content_digest,
  canonical_content,
  acceptance_profile
)
SELECT
  entry->>'policy_id',
  entry->>'version',
  content_digest,
  entry - 'acceptance_profile',
  entry->'acceptance_profile'
FROM incoming_policy_publications
ON CONFLICT (policy_id, version) DO NOTHING;

INSERT INTO policies (
  policy_id,
  version,
  name,
  description,
  category,
  enforcement,
  jurisdictions,
  region_aliases,
  policy_categories,
  channels,
  effective_date,
  sunset_date,
  governance_domains,
  source_url,
  source_name,
  issuer,
  acceptance_profile,
  policy,
  guidance,
  exemplars,
  ext,
  source_type,
  review_status
)
SELECT
  entry->>'policy_id',
  entry->>'version',
  entry->>'name',
  entry->>'description',
  entry->>'category',
  entry->>'enforcement',
  COALESCE(entry->'jurisdictions', '[]'::jsonb),
  COALESCE(entry->'region_aliases', '{}'::jsonb),
  COALESCE(entry->'policy_categories', '[]'::jsonb),
  entry->'channels',
  entry->>'effective_date',
  entry->>'sunset_date',
  COALESCE(entry->'governance_domains', '[]'::jsonb),
  entry->>'source_url',
  entry->>'source_name',
  entry->'issuer',
  entry->'acceptance_profile',
  entry->>'policy',
  entry->>'guidance',
  entry->'exemplars',
  entry->'ext',
  'registry',
  'approved'
FROM incoming_policy_publications
WHERE is_current
ON CONFLICT (policy_id) DO UPDATE SET
  version = EXCLUDED.version,
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  category = EXCLUDED.category,
  enforcement = EXCLUDED.enforcement,
  jurisdictions = EXCLUDED.jurisdictions,
  region_aliases = EXCLUDED.region_aliases,
  policy_categories = EXCLUDED.policy_categories,
  channels = EXCLUDED.channels,
  effective_date = EXCLUDED.effective_date,
  sunset_date = EXCLUDED.sunset_date,
  governance_domains = EXCLUDED.governance_domains,
  source_url = EXCLUDED.source_url,
  source_name = EXCLUDED.source_name,
  issuer = EXCLUDED.issuer,
  acceptance_profile = EXCLUDED.acceptance_profile,
  policy = EXCLUDED.policy,
  guidance = EXCLUDED.guidance,
  exemplars = EXCLUDED.exemplars,
  ext = EXCLUDED.ext,
  review_status = 'approved'
WHERE (
    policies.version = EXCLUDED.version
    OR (policies.policy_id = 'eu_dsa_political_targeting' AND policies.version = '1.0.0' AND EXCLUDED.version = '2.0.0')
  )
  AND policies.source_type = 'registry'
  AND EXISTS (
    SELECT 1
    FROM policy_publications publication
    JOIN incoming_policy_publications incoming
      ON incoming.entry->>'policy_id' = publication.policy_id
     AND incoming.entry->>'version' = publication.version
     AND incoming.content_digest = publication.content_digest
     AND publication.acceptance_profile IS NOT DISTINCT FROM incoming.entry->'acceptance_profile'
    WHERE publication.policy_id = EXCLUDED.policy_id
      AND publication.version = EXCLUDED.version
  );
