/**
 * Integration tests for the AAO agent resolver routes:
 *
 *   GET /api/registry/agents/resolve
 *   GET /api/registry/agents/jwks
 *
 * The integration surface here is "wire-shape end-to-end": we drive the
 * resolver through supertest against an Express app that mounts ONLY the
 * two new routes, with the upstream fetchers mocked.
 *
 * Mocks:
 *  - `capabilities-fetcher` → returns a fixture capabilities response so we
 *    don't need a real MCP server to interrogate.
 *  - `safeFetch` → returns fixture brand.json and JWKS bodies so we don't
 *    contact the network. We sign a fixture token with a real Ed25519
 *    keypair generated by `jose` so the JOSE round-trip exercise is real
 *    (closes the "would jose accept this JWKS" gap).
 *
 * What the tests cover (corresponds to the spec §"Compliance impact"
 * variants):
 *
 * 1. Happy path — eTLD+1 match, key_origins consistent → 200, full body
 *    shape, JOSE round-trip succeeds.
 * 2. brand_url omitted → 502 with `request_signature_brand_url_missing`.
 * 3. brand.json doesn't list the agent → 502 with
 *    `request_signature_agent_not_in_brand_json`.
 * 4. eTLD+1 mismatch with no delegation → 502 with
 *    `request_signature_brand_origin_mismatch`.
 * 5. eTLD+1 mismatch WITH `authorized_operators[]` delegation → passes.
 * 6. key_origins mismatch → 502 with
 *    `request_signature_key_origin_mismatch`.
 * 7. signing declared without key_origins → 502 with
 *    `request_signature_key_origin_missing` (round-2 enforcement).
 * 8. brand.json ambiguous → 502 with
 *    `request_signature_brand_json_ambiguous`.
 * 9. JWKS endpoint propagates upstream Cache-Control byte-for-byte and
 *    surfaces `X-AAO-Trace-URL` / `X-AAO-Upstream-JWKS-URI` headers.
 */
import { describe, it, expect, beforeAll, beforeEach, afterAll, vi } from "vitest";
import express from "express";
import request from "supertest";
import { generateKeyPair, exportJWK, SignJWT, jwtVerify, createLocalJWKSet, calculateJwkThumbprint } from "jose";

// Hoist the mocks so both modules they shadow stay non-real for the
// duration of the test file.
const capsFetcherMock = vi.hoisted(() => vi.fn());
vi.mock("../../src/registry/agent-resolver/capabilities-fetcher.js", () => ({
  fetchCapabilities: (...args: unknown[]) => capsFetcherMock(...args),
}));

const safeFetchMock = vi.hoisted(() => vi.fn());
vi.mock("../../src/utils/url-security.js", async (importOriginal) => {
  const actual = await importOriginal<Record<string, unknown>>();
  return { ...actual, safeFetch: (...args: unknown[]) => safeFetchMock(...args) };
});

// Imports go AFTER the mocks so module load picks up the mocked surfaces.
import { resolveAgent, getAgentJwks } from "../../src/registry/agent-resolver/index.js";
import { AgentResolverError } from "../../src/registry/agent-resolver/errors.js";
import type { Jwk } from "../../src/registry/agent-resolver/jwks-fetcher.js";
import { TtlCache, TokenBucketRateLimiter } from "../../src/registry/agent-resolver/cache.js";

// Per-test fixture state. The resolver normally holds process-global cache
// + rate-limiter singletons; tests inject fresh instances so a hot
// preceding test can't drain the shared bucket.
let testRateLimiter: TokenBucketRateLimiter;
let testBrandJsonCache: TtlCache<unknown>;
let testCapabilitiesCache: TtlCache<unknown>;

const AGENT_URL = "https://buyer.example.com/mcp";
const BRAND_URL = "https://example.com/.well-known/brand.json";
const JWKS_URI = "https://keys.example.com/.well-known/jwks.json";

interface KeyMaterial {
  publicJwk: Jwk;
  privateKey: CryptoKey;
  publicKey: CryptoKey;
  kid: string;
}

async function generateEd25519Material(): Promise<KeyMaterial> {
  const { publicKey, privateKey } = await generateKeyPair("EdDSA", {
    crv: "Ed25519",
    extractable: true,
  });
  const jwk = await exportJWK(publicKey);
  jwk.alg = "EdDSA";
  jwk.use = "sig";
  jwk.key_ops = ["verify"];
  // Real `kid` derivation per RFC 7638 (matches what production publishers do).
  jwk.kid = await calculateJwkThumbprint(jwk);
  (jwk as Jwk).adcp_use = "request-signing";
  return { publicJwk: jwk as Jwk, privateKey, publicKey, kid: jwk.kid };
}

function fakeFetchResponse(
  body: unknown,
  init: { status?: number; headers?: Record<string, string> } = {},
): Response {
  return new Response(typeof body === "string" ? body : JSON.stringify(body), {
    status: init.status ?? 200,
    headers: {
      "content-type": "application/json",
      ...init.headers,
    },
  });
}

interface FixtureOptions {
  brandJson?: Record<string, unknown>;
  jwks?: { keys: Jwk[] };
  jwksHeaders?: Record<string, string>;
  capabilities?: Record<string, unknown>;
}

function arm(opts: FixtureOptions): void {
  const brandJson = opts.brandJson ?? {
    agents: [
      {
        type: "buying",
        url: AGENT_URL,
        id: "buyer_main",
        jwks_uri: JWKS_URI,
      },
    ],
  };
  capsFetcherMock.mockReset();
  capsFetcherMock.mockImplementation(async () => ({
    data: opts.capabilities ?? {
      brand_url: BRAND_URL,
      adcp: { major_versions: [3] },
      supported_protocols: ["media_buy"],
    },
    fetched_at: new Date().toISOString(),
    cache_control: null,
    bytes: 1234,
    from_cache: false,
  }));
  safeFetchMock.mockReset();
  safeFetchMock.mockImplementation(async (url: string) => {
    if (url === BRAND_URL) {
      return fakeFetchResponse(brandJson, {
        headers: {
          etag: "\"b9f0\"",
          "last-modified": "Wed, 29 Apr 2026 18:00:00 GMT",
          "cache-control": "max-age=300, public",
        },
      });
    }
    if (url === JWKS_URI || url.endsWith("/.well-known/jwks.json")) {
      const jwks = opts.jwks ?? { keys: [] };
      return fakeFetchResponse(jwks, {
        headers: {
          "cache-control": "max-age=300",
          ...opts.jwksHeaders,
        },
      });
    }
    return fakeFetchResponse({ error: "no fixture" }, { status: 404 });
  });
}

function clearResolverState(): void {
  // The resolver module holds a process-global cache; reset between cases
  // by importing the cache and clearing it via the fresh-flag flow on each
  // resolveAgent call we make in this test file.
}

describe("AAO agent resolver — integration", () => {
  let key: KeyMaterial;
  let app: express.Express;

  beforeAll(async () => {
    key = await generateEd25519Material();

    app = express();
    app.get("/api/registry/agents/resolve", async (req, res) => {
      const agentUrlRaw = req.query.agent_url;
      if (typeof agentUrlRaw !== "string" || agentUrlRaw.length === 0) {
        return res.status(400).json({
          error: { code: "request_signature_invalid_agent_url" },
        });
      }
      try {
        const out = await resolveAgent(agentUrlRaw, {
          fresh: true,
          rateLimiter: testRateLimiter,
          brandJsonCache: testBrandJsonCache as never,
          capabilitiesCache: testCapabilitiesCache as never,
        });
        return res.status(200).json(out);
      } catch (err) {
        if (err instanceof AgentResolverError) {
          const { trace, freshness, ...detailFields } = err.detail as typeof err.detail & {
            trace?: unknown;
            freshness?: unknown;
          };
          return res.status(err.httpStatus).json({
            error: { code: err.code, detail: detailFields },
            aao_signed: false,
            freshness: freshness ?? "unknown",
            trace: trace ?? [],
          });
        }
        return res.status(500).json({ error: { code: "internal_error" } });
      }
    });
    app.get("/api/registry/agents/jwks", async (req, res) => {
      const agentUrlRaw = req.query.agent_url;
      if (typeof agentUrlRaw !== "string" || agentUrlRaw.length === 0) {
        return res.status(400).json({
          error: { code: "request_signature_invalid_agent_url" },
        });
      }
      try {
        const out = await getAgentJwks(agentUrlRaw, {
          fresh: true,
          rateLimiter: testRateLimiter,
          brandJsonCache: testBrandJsonCache as never,
          capabilitiesCache: testCapabilitiesCache as never,
        });
        for (const [name, value] of Object.entries(out.passthroughHeaders)) {
          res.setHeader(name, value);
        }
        res.setHeader("Content-Type", "application/jwk-set+json");
        res.setHeader("X-AAO-Resolver-Age", String(out.resolverAgeSeconds));
        res.setHeader("X-AAO-Upstream-JWKS-URI", out.jwksUri);
        const traceUrl = `/api/registry/agents/resolve?agent_url=${encodeURIComponent(agentUrlRaw)}`;
        res.setHeader("X-AAO-Trace-URL", traceUrl);
        return res.status(200).send(JSON.stringify(out.jwks));
      } catch (err) {
        if (err instanceof AgentResolverError) {
          const traceUrl = `/api/registry/agents/resolve?agent_url=${encodeURIComponent(agentUrlRaw as string)}`;
          res.setHeader("X-AAO-Trace-URL", traceUrl);
          return res.status(err.httpStatus).json({
            error: { code: err.code },
            aao_signed: false,
          });
        }
        return res.status(500).json({ error: { code: "internal_error" } });
      }
    });
  });

  afterAll(() => {
    capsFetcherMock.mockReset();
    safeFetchMock.mockReset();
  });

  beforeEach(() => {
    clearResolverState();
    // Fresh per-test state so a previous case can't drain the bucket.
    testRateLimiter = new TokenBucketRateLimiter({
      capacity: 100,
      refillPerSecond: 100,
    });
    testBrandJsonCache = new TtlCache({ defaultTtlMs: 60_000 });
    testCapabilitiesCache = new TtlCache({ defaultTtlMs: 60_000 });
  });

  it("happy path returns 200 with full body shape, trace, freshness, JOSE round-trip", async () => {
    arm({ jwks: { keys: [key.publicJwk] } });
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: AGENT_URL });

    expect(res.status).toBe(200);
    const body = res.body;
    expect(body.agent_url).toBe(AGENT_URL);
    expect(body.brand_url).toBe(BRAND_URL);
    expect(body.operator_domain).toBe("example.com");
    expect(body.agent_entry).toMatchObject({
      type: "buying",
      url: AGENT_URL,
      id: "buyer_main",
      jwks_uri: JWKS_URI,
    });
    expect(body.jwks_uri).toBe(JWKS_URI);
    expect(body.jwks.keys).toHaveLength(1);
    expect(body.signing_keys_pin).toBeNull();
    expect(body.aao_signed).toBe(false);
    expect(body.consistency.origin_binding).toBe("etld1_match");
    expect(body.consistency.key_origin_match).toBe(true);
    expect(body.source).toBe("live");
    expect(["fresh", "unknown", "stale"]).toContain(body.freshness);
    expect(Array.isArray(body.trace)).toBe(true);
    expect(body.trace.length).toBe(3);
    expect(body.trace.map((s: { step: string }) => s.step)).toEqual(["capabilities", "brand_json", "jwks"]);
    // Privacy: query strings must be stripped from the trace URL.
    for (const step of body.trace) {
      expect(typeof step.url).toBe("string");
      expect(step.url).not.toContain("agent_url=");
    }

    // JOSE round-trip — sign with the fixture private key and verify
    // against the JWKS the resolver returned.
    const token = await new SignJWT({ sub: "ok" })
      .setProtectedHeader({ alg: "EdDSA", kid: key.kid })
      .setIssuer(AGENT_URL)
      .setIssuedAt()
      .sign(key.privateKey);
    const jwks = createLocalJWKSet(body.jwks);
    const { payload } = await jwtVerify(token, jwks, {
      algorithms: ["EdDSA"],
      issuer: AGENT_URL,
    });
    expect(payload.sub).toBe("ok");
  });

  it("returns request_signature_brand_url_missing when brand_url is absent", async () => {
    arm({
      capabilities: {
        adcp: { major_versions: [3] },
        supported_protocols: ["media_buy"],
      },
      jwks: { keys: [key.publicJwk] },
    });
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(502);
    expect(res.body.error.code).toBe("request_signature_brand_url_missing");
    expect(res.body.aao_signed).toBe(false);
    expect(Array.isArray(res.body.trace)).toBe(true);
  });

  it("returns request_signature_agent_not_in_brand_json when brand.json lacks the agent", async () => {
    arm({
      brandJson: {
        agents: [{ type: "buying", url: "https://other.example.com/mcp", id: "x" }],
      },
      jwks: { keys: [key.publicJwk] },
    });
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(502);
    expect(res.body.error.code).toBe("request_signature_agent_not_in_brand_json");
  });

  it("returns request_signature_brand_origin_mismatch on cross-eTLD+1 with no delegation", async () => {
    arm({
      capabilities: {
        brand_url: "https://nike.com/.well-known/brand.json",
        adcp: { major_versions: [3] },
        supported_protocols: ["media_buy"],
      },
      brandJson: {
        agents: [{ type: "buying", url: "https://buyer.example.com/mcp", id: "x" }],
      },
      jwks: { keys: [key.publicJwk] },
    });
    safeFetchMock.mockReset();
    safeFetchMock.mockImplementation(async (url: string) => {
      if (url === "https://nike.com/.well-known/brand.json") {
        return fakeFetchResponse(
          {
            agents: [{ type: "buying", url: "https://buyer.example.com/mcp", id: "x" }],
          },
          { headers: { "cache-control": "max-age=300" } },
        );
      }
      return fakeFetchResponse({ keys: [key.publicJwk] }, {
        headers: { "cache-control": "max-age=300" },
      });
    });

    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(502);
    expect(res.body.error.code).toBe("request_signature_brand_origin_mismatch");
    expect(res.body.error.detail.agent_etld1).toBe("example.com");
    expect(res.body.error.detail.brand_url_etld1).toBe("nike.com");
  });

  it("passes when authorized_operators[] delegates the agent's eTLD+1", async () => {
    capsFetcherMock.mockReset();
    capsFetcherMock.mockImplementation(async () => ({
      data: {
        brand_url: "https://nike.com/.well-known/brand.json",
        adcp: { major_versions: [3] },
        supported_protocols: ["media_buy"],
      },
      fetched_at: new Date().toISOString(),
      cache_control: null,
      bytes: 0,
      from_cache: false,
    }));
    safeFetchMock.mockReset();
    safeFetchMock.mockImplementation(async (url: string) => {
      if (url === "https://nike.com/.well-known/brand.json") {
        return fakeFetchResponse(
          {
            agents: [
              { type: "buying", url: "https://agent.scope3.com/mcp", id: "x", jwks_uri: JWKS_URI },
            ],
            authorized_operators: [{ domain: "scope3.com", brands: ["*"] }],
          },
          { headers: { "cache-control": "max-age=300" } },
        );
      }
      return fakeFetchResponse({ keys: [key.publicJwk] }, {
        headers: { "cache-control": "max-age=300" },
      });
    });
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: "https://agent.scope3.com/mcp" });
    expect(res.status).toBe(200);
    expect(res.body.consistency.origin_binding).toBe("authorized_operator");
  });

  it("returns request_signature_key_origin_mismatch when key_origins host disagrees with jwks_uri host", async () => {
    arm({
      capabilities: {
        brand_url: BRAND_URL,
        adcp: { major_versions: [3] },
        supported_protocols: ["media_buy"],
        request_signing: { supported: true, supported_for: ["create_media_buy"] },
        identity: {
          key_origins: { request_signing: "https://other-keys.example.com" },
        },
      },
      jwks: { keys: [key.publicJwk] },
    });
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(502);
    expect(res.body.error.code).toBe("request_signature_key_origin_mismatch");
    expect(res.body.error.detail.purpose).toBe("request_signing");
    expect(res.body.error.detail.expected_origin).toBe("https://other-keys.example.com");
    expect(res.body.error.detail.actual_origin).toBe("https://keys.example.com");
  });

  it("returns request_signature_key_origin_missing when signing declared without key_origins", async () => {
    arm({
      capabilities: {
        brand_url: BRAND_URL,
        adcp: { major_versions: [3] },
        supported_protocols: ["media_buy"],
        request_signing: { supported: true, supported_for: ["create_media_buy"] },
        // identity intentionally absent — round-2 spec says AAO MUST itself
        // enforce key_origins required-when, not pass through.
      },
      jwks: { keys: [key.publicJwk] },
    });
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(502);
    expect(res.body.error.code).toBe("request_signature_key_origin_missing");
    expect(res.body.error.detail.purpose).toBe("request_signing");
  });

  it("returns request_signature_brand_json_ambiguous on multiple matching agents[] entries", async () => {
    arm({
      brandJson: {
        agents: [
          { type: "buying", url: AGENT_URL, id: "first", jwks_uri: JWKS_URI },
          { type: "buying", url: AGENT_URL, id: "duplicate", jwks_uri: JWKS_URI },
        ],
      },
      jwks: { keys: [key.publicJwk] },
    });
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(502);
    expect(res.body.error.code).toBe("request_signature_brand_json_ambiguous");
    expect(res.body.error.detail.matched_count).toBe(2);
    expect(res.body.error.detail.matched_entries).toHaveLength(2);
  });

  it("/jwks endpoint propagates upstream Cache-Control byte-for-byte and surfaces trace URL header", async () => {
    arm({
      jwks: { keys: [key.publicJwk] },
      jwksHeaders: { "cache-control": "max-age=42, must-revalidate" },
    });
    const res = await request(app)
      .get("/api/registry/agents/jwks")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(200);
    expect(res.headers["content-type"]).toContain("application/jwk-set+json");
    // Cache-Control propagated byte-for-byte (escape-html is a no-op for safe chars).
    expect(res.headers["cache-control"]).toBe("max-age=42, must-revalidate");
    expect(res.headers["x-aao-upstream-jwks-uri"]).toBe(JWKS_URI);
    expect(res.headers["x-aao-trace-url"]).toContain("/api/registry/agents/resolve");
    expect(res.headers["x-aao-trace-url"]).toContain(encodeURIComponent(AGENT_URL));
    // Body is RFC 7517 pure — `keys` only.
    const parsed = JSON.parse(res.text);
    expect(Object.keys(parsed)).toEqual(["keys"]);
    expect(parsed.keys[0].kid).toBe(key.kid);
  });

  it("/jwks JOSE round-trip works against the resolver-served JWKS", async () => {
    arm({ jwks: { keys: [key.publicJwk] } });
    const res = await request(app)
      .get("/api/registry/agents/jwks")
      .query({ agent_url: AGENT_URL });
    expect(res.status).toBe(200);

    const jwks = createLocalJWKSet(JSON.parse(res.text));
    const token = await new SignJWT({ sub: "round-trip" })
      .setProtectedHeader({ alg: "EdDSA", kid: key.kid })
      .setIssuer(AGENT_URL)
      .setIssuedAt()
      .sign(key.privateKey);
    const { payload } = await jwtVerify(token, jwks, {
      algorithms: ["EdDSA"],
      issuer: AGENT_URL,
    });
    expect(payload.sub).toBe("round-trip");
  });

  it("rejects oversize agent_url with 414 before any fetch", async () => {
    capsFetcherMock.mockReset();
    safeFetchMock.mockReset();
    const long = "https://example.com/" + "a".repeat(3000);
    const res = await request(app)
      .get("/api/registry/agents/resolve")
      .query({ agent_url: long });
    expect(res.status).toBe(414);
    expect(res.body.error.code).toBe("request_signature_invalid_agent_url");
    expect(capsFetcherMock).not.toHaveBeenCalled();
    expect(safeFetchMock).not.toHaveBeenCalled();
  });
});
