#!/bin/sh

HUSKY_INIT="${XDG_CONFIG_HOME:-$HOME/.config}/husky/init.sh"
[ -f "$HUSKY_INIT" ] && . "$HUSKY_INIT"
[ "${HUSKY-}" = "0" ] && exit 0
export PATH="node_modules/.bin:$PATH"

bash scripts/check-image-quality.sh
npm run precommit
